const base = () => import.meta.env.BASE_URL;

const p = (path) => `${base()}${path}`;

export const sections = [
  { id: 'open', label: 'Welcome' },
  { id: 'meet', label: 'Introduction' },
  { id: 'vision', label: 'Vision' },
  { id: 'opp', label: 'Opportunity' },
  { id: 'why', label: 'Why ERGO' },
  { id: 'here', label: 'Why here' },
  { id: 'intro', label: 'ERGO' },
  { id: 'vgrg', label: 'VG & RG' },
  { id: 'earn', label: 'Earn' },
  { id: 'fragen', label: 'Fragen' },
];

export const slides = [
  {
    id: 'open',
    section: 'open',
    kicker: 'ERGO  ·  Abedin',
    title: 'Journey to being Independent',
    line: 'Why ERGO. Why now.',
    photos: [
      { src: p('photos/ergo/hq.jpg'), w: 4.6, h: 2.7, x: 2.9, y: 0.7, z: -1.0, ry: -0.14 },
    ],
    cam: { x: -0.4, y: 0.3, z: 8.6, tx: 1.4, ty: 0.22, tz: 0 },
    trail: false,
  },
  {
    id: 'meet-1',
    section: 'meet',
    kicker: '01  ·  Introduction',
    title: 'Who is Abedin.',
    line: '',
    photos: [
      { src: p('photos/abedin/portrait.jpg'), w: 4.35, h: 2.9, x: 2.65, y: 0.75, z: -0.9, ry: -0.12 },
      { src: p('photos/abedin/boat.jpg'), w: 2.15, h: 1.53, x: 4.55, y: -0.55, z: 0.5, ry: -0.1 },
    ],
    cam: { x: -0.45, y: 0.2, z: 8.4, tx: 1.55, ty: 0.2, tz: 0 },
    trail: true,
  },
  {
    id: 'vision-1',
    section: 'vision',
    kicker: '02  ·  The Vision',
    title: 'Vision for Bangladesh',
    line: 'Clean it up. Make it like Singapore.',
    facts: [
      { v: 'Bhairab', k: 'Wealthy. Very dirty.' },
      { v: 'Inside', k: 'AC · elevators' },
      { v: 'Outside', k: 'Dirty streets' },
      { v: 'Plan', k: 'City first, then expand' },
    ],
    photos: [
      { src: p('photos/abedin/before.jpg'), w: 2.9, h: 2.12, x: 1.95, y: 0.95, z: -0.75, ry: 0.1 },
      { src: p('photos/abedin/roundabout.jpg'), w: 3.55, h: 2.22, x: 4.5, y: 0.4, z: -0.12, ry: -0.12 },
    ],
    cam: { x: -0.35, y: 0.22, z: 8.5, tx: 2.35, ty: 0.35, tz: 0 },
    trail: false,
  },
  {
    id: 'opp-1',
    section: 'opp',
    kicker: '03  ·  Opportunity',
    title: 'The service gap.',
    line: 'Language and distrust of local banks.',
    cards: [
      { label: 'New arrivals', sub: 'Students. First setup.', kicker: 'Segment 01', x: 3.05, y: 0.5, z: 0.15, ry: 0.08 },
      { label: 'Established', sub: 'Live here. Little German.', kicker: 'Segment 02', x: 5.35, y: 0.5, z: 0.15, ry: -0.1 },
    ],
    cam: { x: -0.2, y: 0.28, z: 8.4, tx: 3.3, ty: 0.28, tz: 0 },
    trail: true,
  },
  {
    id: 'opp-2',
    section: 'opp',
    kicker: '03  ·  Opportunity',
    title: 'The market is growing.',
    line: 'South Asian nationals in Germany. IN, PK, BD, SL.',
    facts: [
      { v: '~160k', k: '2017' },
      { v: '~450k', k: '2024' },
    ],
    photos: [
      { src: p('photos/opportunity/nationals.jpg'), w: 4.5, h: 2.81, x: 3.15, y: 0.75, z: -0.55, ry: -0.08 },
    ],
    cam: { x: -0.45, y: 0.2, z: 8.4, tx: 1.7, ty: 0.35, tz: 0 },
    trail: false,
  },
  {
    id: 'opp-3',
    section: 'opp',
    kicker: '03  ·  Opportunity',
    title: 'The student pipeline.',
    line: 'South Asian students in Germany, approx.',
    facts: [
      { v: '~40k', k: '2020' },
      { v: '~90k', k: '2025' },
    ],
    photos: [
      { src: p('photos/opportunity/students.jpg'), w: 4.5, h: 2.81, x: 3.15, y: 0.75, z: -0.55, ry: -0.08 },
    ],
    cam: { x: -0.45, y: 0.2, z: 8.4, tx: 1.7, ty: 0.35, tz: 0 },
    trail: false,
  },
  {
    id: 'opp-4',
    section: 'opp',
    kicker: '03  ·  Opportunity',
    title: 'They stay.',
    line: 'IAB immigrant stay intentions. A long-term book.',
    facts: [
      { v: '58%', k: 'Permanent' },
      { v: '30%', k: 'Undecided' },
      { v: '12%', k: 'Temporary' },
    ],
    photos: [
      { src: p('photos/opportunity/stay.jpg'), w: 3.15, h: 3.15, x: 3.35, y: 0.4, z: -0.35, ry: -0.08 },
    ],
    cam: { x: -0.4, y: 0.2, z: 8.3, tx: 1.7, ty: 0.22, tz: 0 },
    trail: false,
  },
  {
    id: 'opp-5',
    section: 'opp',
    kicker: '03  ·  Opportunity',
    title: 'Lifetime value.',
    line: 'Map products to the life they actually live.',
    cards: [
      { label: 'Student', sub: 'Setup. Basic savings.', kicker: 'Stage 01', x: 2.2, y: 1.1, z: 0.05, ry: 0.06 },
      { label: 'Professional', sub: 'Income. Private health.', kicker: 'Stage 02', x: 4.9, y: 1.25, z: 0.3, ry: 0 },
      { label: 'Family', sub: 'Home. Children’s plans.', kicker: 'Stage 03', x: 7.6, y: 1.05, z: 0.05, ry: -0.06 },
    ],
    cam: { x: 0.7, y: 0.5, z: 12.4, tx: 4.9, ty: 0.7, tz: 0 },
    trail: false,
  },
  {
    id: 'why-0',
    section: 'why',
    kicker: '04  ·  Why ERGO',
    title: 'A brand that\nstands in public.',
    line: 'Inter Miami. The German national team.',
    facts: [
      { v: 'DFB', k: 'Official partner' },
      { v: 'Miami', k: 'On the world stage' },
    ],
    photos: [
      { src: p('photos/ergo/miami.jpg'), w: 4.7, h: 2.01, x: 2.55, y: 0.9, z: -0.85, ry: -0.08 },
      { src: p('photos/ergo/dfb.jpg'), w: 2.15, h: 2.15, x: 4.65, y: -0.45, z: 0.4, ry: -0.1 },
    ],
    cam: { x: -0.5, y: 0.22, z: 8.5, tx: 1.55, ty: 0.4, tz: 0 },
    trail: true,
  },
  {
    id: 'why-1',
    section: 'why',
    kicker: '04  ·  Why ERGO',
    title: 'Why I chose ERGO',
    line: 'Fairness is the core reason.',
    facts: [
      { v: '10+ years', k: 'Restaurant chef' },
    ],
    photos: [
      { src: p('photos/ergo/sign.jpg'), w: 3.35, h: 3.35, x: 3.25, y: 0.4, z: -0.45, ry: -0.1 },
    ],
    cam: { x: -0.45, y: 0.2, z: 8.3, tx: 1.7, ty: 0.22, tz: 0 },
    trail: false,
  },
  {
    id: 'why-2',
    section: 'why',
    kicker: '04  ·  Why ERGO',
    title: 'The salary\nstays flat.',
    line: 'Even if the boss earns millions.',
    cards: [
      { label: 'Restaurant', sub: 'Work more. Pay stays the same.', kicker: 'Before', x: 3.05, y: 0.45, z: 0.2, ry: 0.08 },
      { label: 'ERGO', sub: 'More work. More pay.', kicker: 'After', x: 5.35, y: 0.45, z: 0.2, ry: -0.1 },
    ],
    cam: { x: -0.15, y: 0.28, z: 8.3, tx: 3.3, ty: 0.28, tz: 0 },
    trail: false,
  },
  {
    id: 'why-3',
    section: 'why',
    kicker: '04  ·  Why ERGO',
    title: 'More work. More pay.',
    line: 'Self-accountability. Income follows effort.',
    facts: [
      { v: 'Effort', k: 'Sets the income' },
      { v: 'You', k: 'Own the result' },
    ],
    cam: { x: 0, y: 0.25, z: 8.4, tx: 0.3, ty: 0.15, tz: 0 },
    trail: false,
  },
  {
    id: 'here-1',
    section: 'here',
    kicker: '05  ·  Why I am here',
    title: 'Why I am here.',
    line: 'Solve problems for restaurant workers.',
    facts: [
      { v: '90%', k: 'Do not work commercially' },
    ],
    cam: { x: -0.15, y: 0.22, z: 8.4, tx: 0.4, ty: 0.12, tz: 0 },
    trail: true,
  },
  {
    id: 'here-2',
    section: 'here',
    kicker: '05  ·  Why I am here',
    title: 'Ten years.\nOne goal.',
    line: 'Open restaurants. Then the reach ran out.',
    cards: [
      { label: '5 restaurants', sub: 'Would only serve family.', kicker: 'The plan', x: 3.15, y: 0.45, z: 0.15, ry: 0.08 },
      { label: 'Too small', sub: 'Not enough reach.', kicker: 'The limit', x: 5.35, y: 0.45, z: 0.15, ry: -0.1 },
    ],
    cam: { x: -0.2, y: 0.28, z: 8.4, tx: 3.3, ty: 0.28, tz: 0 },
    trail: false,
  },
  {
    id: 'here-3',
    section: 'here',
    kicker: '05  ·  Why I am here',
    title: 'A bigger reach.',
    line: 'Help the Bangladeshi community in Germany.',
    facts: [
      { v: 'Independent', k: 'Financially. Families secure.' },
      { v: '50%', k: 'Community in 5 years' },
    ],
    cam: { x: -0.1, y: 0.22, z: 8.5, tx: 0.35, ty: 0.12, tz: 0 },
    trail: false,
  },
  {
    id: 'intro-1',
    section: 'intro',
    kicker: '06  ·  ERGO',
    title: 'A century of capital.',
    line: 'Multi-billion group. Munich Re at the core.',
    facts: [
      { v: '100+', k: 'Years of capital' },
      { v: 'Munich Re', k: 'Behind the group' },
    ],
    photos: [
      { src: p('photos/ergo/hq.jpg'), w: 4.55, h: 2.7, x: 2.9, y: 0.9, z: -0.8, ry: -0.1 },
    ],
    cam: { x: -0.55, y: 0.18, z: 7.9, tx: 1.5, ty: 0.4, tz: -0.4 },
    trail: true,
  },
  {
    id: 'intro-2',
    section: 'intro',
    kicker: '06  ·  ERGO',
    title: 'The magic triangle.',
    line: 'Every great investment needs all three.',
    cards: [
      { label: 'Security', sub: 'Capital that holds.', kicker: '01  Sicherheit', x: 2.2, y: 1.1, z: 0.05, ry: 0.06 },
      { label: 'Returns', sub: 'Growth you can keep.', kicker: '02  Gewinne', x: 4.9, y: 1.25, z: 0.3, ry: 0 },
      { label: 'Flexibility', sub: 'You stay in control.', kicker: '03  Flexibilität', x: 7.6, y: 1.05, z: 0.05, ry: -0.06 },
    ],
    cam: { x: 0.7, y: 0.5, z: 12.4, tx: 4.9, ty: 0.7, tz: 0 },
    trail: false,
  },
  {
    id: 'intro-3',
    section: 'intro',
    kicker: '06  ·  ERGO',
    title: 'A product that adapts.',
    line: 'The client chooses what matters most.',
    photos: [
      { src: p('photos/ergo/office.jpg'), w: 4.4, h: 2.48, x: 2.95, y: 0.9, z: -0.75, ry: -0.1 },
    ],
    cam: { x: -0.4, y: 0.2, z: 8.1, tx: 1.5, ty: 0.35, tz: 0 },
    trail: false,
  },
  {
    id: 'vgrg-1',
    section: 'vgrg',
    kicker: '07  ·  VG & RG',
    title: 'Two paths. One career.',
    line: 'Help clients. Build a team.',
    cards: [
      { label: 'VG', sub: 'Protect people’s wealth.', kicker: 'Clients', x: 3.35, y: 0.9, z: 0.15, ry: 0.08 },
      { label: 'RG', sub: 'Build a team that lasts.', kicker: 'People', x: 5.35, y: 0.9, z: 0.15, ry: -0.1 },
    ],
    cam: { x: -0.2, y: 0.32, z: 9.2, tx: 3.4, ty: 0.45, tz: 0 },
    trail: true,
  },
  {
    id: 'vgrg-2',
    section: 'vgrg',
    kicker: '07  ·  VG',
    title: 'Protect people’s wealth.',
    line: 'The client conversation. Security, returns, flexibility.',
    photos: [
      { src: p('photos/ergo/hq.jpg'), w: 4.35, h: 2.58, x: 2.95, y: 0.9, z: -0.8, ry: -0.1 },
    ],
    cam: { x: -0.4, y: 0.18, z: 8.2, tx: 1.5, ty: 0.32, tz: 0 },
    trail: false,
  },
  {
    id: 'vgrg-3',
    section: 'vgrg',
    kicker: '07  ·  RG',
    title: 'Build a team that lasts.',
    line: 'The people path. Partners who want more.',
    photos: [
      { src: p('photos/ergo/office.jpg'), w: 4.3, h: 2.42, x: 2.95, y: 0.95, z: -0.75, ry: -0.12 },
    ],
    cam: { x: -0.35, y: 0.2, z: 8.3, tx: 1.5, ty: 0.32, tz: 0 },
    trail: false,
  },
  {
    id: 'earn-1',
    section: 'earn',
    kicker: '08  ·  How partners earn',
    title: 'First: your own work.',
    line: 'Paid for the clients you serve.',
    cards: [
      { label: 'Produktion', sub: 'Your own client work.', kicker: 'Income 01', x: 3.25, y: 0.45, z: 0.2, ry: -0.08 },
    ],
    cam: { x: -0.45, y: 0.22, z: 8.4, tx: 1.7, ty: 0.2, tz: 0 },
    trail: true,
  },
  {
    id: 'earn-2',
    section: 'earn',
    kicker: '08  ·  How partners earn',
    title: 'Then: the people you lead.',
    line: 'Leadership multiplies what you already do well.',
    cards: [
      { label: 'Führung', sub: 'Paid for the people you lead.', kicker: 'Income 02', x: 3.15, y: 0.45, z: 0.15, ry: 0.08 },
      { label: 'System', sub: 'A structure that scales.', kicker: 'Income 02', x: 5.2, y: 0.45, z: 0.15, ry: -0.1 },
    ],
    cam: { x: -0.4, y: 0.28, z: 8.8, tx: 3.1, ty: 0.28, tz: 0 },
    trail: false,
  },
  {
    id: 'earn-3',
    section: 'earn',
    kicker: '08  ·  How partners earn',
    title: 'Training. System. Support.',
    line: 'Nobody is left alone with the craft.',
    facts: [
      { v: 'Tue + Thu', k: '19:00–21:00' },
      { v: 'Sales', k: 'Recruiting · Lead' },
    ],
    photos: [
      { src: p('photos/ergo/office.jpg'), w: 4.4, h: 2.48, x: 2.9, y: 0.85, z: -0.7, ry: -0.1 },
    ],
    cam: { x: -0.4, y: 0.18, z: 8.2, tx: 1.45, ty: 0.28, tz: 0 },
    trail: false,
  },
  {
    id: 'fragen-1',
    section: 'fragen',
    kicker: '09  ·  Fragen',
    title: 'Your turn. Ask anything.',
    line: 'No script from here. Just honesty.',
    photos: [
      { src: p('photos/ergo/hq.jpg'), w: 3.6, h: 2.15, x: 3.2, y: 0.7, z: -0.4, ry: -0.1 },
    ],
    cam: { x: -0.45, y: 0.18, z: 8.1, tx: 1.5, ty: 0.22, tz: 0 },
    trail: true,
  },
  {
    id: 'fragen-2',
    section: 'fragen',
    kicker: '09  ·  Fragen',
    title: 'Shall we start together?',
    line: 'The next step is yours.',
    photos: [
      { src: p('photos/ergo/office.jpg'), w: 4.2, h: 2.36, x: 3.05, y: 0.75, z: -0.5, ry: -0.08 },
    ],
    cam: { x: -0.35, y: 0.2, z: 8.4, tx: 1.5, ty: 0.22, tz: 0 },
    trail: false,
  },
];
