const base = () => import.meta.env.BASE_URL;

const p = (path) => `${base()}${path}`;

export const sections = [
  { id: 'open', label: 'Welcome' },
  { id: 'why', label: 'Why ERGO' },
  { id: 'vision', label: 'The Vision' },
  { id: 'intro', label: 'ERGO' },
  { id: 'vgrg', label: 'VG & RG' },
  { id: 'earn', label: 'Earn' },
  { id: 'fragen', label: 'Fragen' },
];

export const slides = [
  {
    id: 'open',
    section: 'open',
    kicker: 'ERGO  ·  Abadin',
    title: 'For Abadin.',
    line: 'Why ERGO. Why now.',
    photos: [
      { src: p('photos/ergo/hq.jpg'), w: 4.4, h: 2.55, x: 3.05, y: 0.85, z: -1.2, ry: -0.16 },
      { src: p('photos/yash/portrait.jpg'), w: 1.7, h: 2.2, x: -3.55, y: 1.15, z: 0.5, ry: 0.14 },
    ],
    cam: { x: 0, y: 0.35, z: 8.6, tx: 0.15, ty: 0.2, tz: 0 },
    trail: false,
  },
  {
    id: 'why-1',
    section: 'why',
    kicker: '01  ·  Why ERGO',
    title: 'Trust at German scale.',
    line: 'A century at the top of the market.',
    photos: [
      { src: p('photos/ergo/hq.jpg'), w: 5.2, h: 3.1, x: 2.2, y: 0.35, z: -0.8, ry: -0.12 },
    ],
    cam: { x: -0.6, y: 0.2, z: 7.8, tx: 1.1, ty: 0.25, tz: -0.6 },
    trail: true,
  },
  {
    id: 'why-2',
    section: 'why',
    kicker: '01  ·  Why ERGO',
    title: 'Munich Re stands behind us.',
    line: 'The world’s largest reinsurer. ERGO is its primary insurer.',
    photos: [
      { src: p('photos/ergo/hq.jpg'), w: 3.6, h: 2.15, x: -3.0, y: 0.9, z: -1.8, ry: 0.2 },
      { src: p('photos/yash/profile.jpg'), w: 2.1, h: 2.5, x: 3.15, y: -0.05, z: 0.2, ry: -0.14 },
    ],
    cam: { x: 0.8, y: 0.15, z: 8.2, tx: -0.2, ty: 0.15, tz: 0 },
    trail: false,
  },
  {
    id: 'why-3',
    section: 'why',
    kicker: '01  ·  Why ERGO',
    title: 'Every fourth German. Ours.',
    line: '25 million customers in Germany. 40 million worldwide.',
    photos: [
      { src: p('photos/ergo/team.jpg'), w: 4.4, h: 2.6, x: 2.6, y: 0.4, z: -1.0, ry: -0.16 },
    ],
    cam: { x: -0.4, y: 0.25, z: 8.0, tx: 1.0, ty: 0.2, tz: -0.4 },
    trail: false,
  },
  {
    id: 'vision-1',
    section: 'vision',
    kicker: '02  ·  The Vision',
    title: 'I am building something real.',
    line: 'Not a job. A long game.',
    photos: [
      { src: p('photos/yash/vision.jpg'), w: 4.8, h: 4.8, x: 2.7, y: 0.15, z: -0.6, ry: -0.1 },
      { src: p('photos/yash/casual.jpg'), w: 2.4, h: 1.8, x: -3.4, y: 0.7, z: 0.5, ry: 0.18 },
    ],
    cam: { x: -0.5, y: 0.1, z: 8.4, tx: 0.6, ty: 0.1, tz: 0 },
    trail: true,
  },
  {
    id: 'vision-2',
    section: 'vision',
    kicker: '02  ·  The Vision',
    title: 'Roots in Bangladesh.',
    line: 'From Dhaka to here — with purpose.',
    photos: [
      { src: p('photos/bangladesh/dhaka.jpg'), w: 4.5, h: 2.55, x: -2.5, y: 0.85, z: -1.6, ry: 0.14 },
      { src: p('photos/bangladesh/padma.jpg'), w: 3.6, h: 2.05, x: 3.1, y: -0.35, z: 0.1, ry: -0.2 },
      { src: p('photos/bangladesh/heritage.jpg'), w: 2.2, h: 1.25, x: 0.2, y: 1.55, z: -0.4, ry: 0.06 },
    ],
    cam: { x: 0.2, y: 0.35, z: 8.8, tx: 0.1, ty: 0.3, tz: 0 },
    trail: false,
  },
  {
    id: 'vision-3',
    section: 'vision',
    kicker: '02  ·  The Vision',
    title: 'Give back. Grow together.',
    line: 'Build a life that lifts more than one person.',
    photos: [
      { src: p('photos/bangladesh/cox.jpg'), w: 4.8, h: 2.7, x: 2.8, y: 0.5, z: -1.2, ry: -0.14 },
      { src: p('photos/yash/vision.jpg'), w: 2.3, h: 2.3, x: -3.3, y: 0.1, z: 0.4, ry: 0.12 },
    ],
    cam: { x: -0.3, y: 0.2, z: 8.1, tx: 0.4, ty: 0.2, tz: 0 },
    trail: false,
  },
  {
    id: 'intro-1',
    section: 'intro',
    kicker: '03  ·  Introduction',
    title: 'A century of capital.',
    line: 'Multi-billion group. Munich Re at the core.',
    photos: [
      { src: p('photos/ergo/hq.jpg'), w: 5.0, h: 3.0, x: 2.4, y: 0.3, z: -0.9, ry: -0.1 },
    ],
    cam: { x: -0.7, y: 0.15, z: 7.6, tx: 1.2, ty: 0.2, tz: -0.5 },
    trail: true,
  },
  {
    id: 'intro-2',
    section: 'intro',
    kicker: '03  ·  Introduction',
    title: 'Security. Returns. Flexibility.',
    line: 'The three points every great investment needs.',
    photos: [],
    cards: [
      { label: 'Sicherheit', x: -2.6, y: 0.3, z: 0 },
      { label: 'Gewinne', x: 0, y: 0.55, z: 0.3 },
      { label: 'Flexibilität', x: 2.6, y: 0.2, z: 0 },
    ],
    cam: { x: 0, y: 0.4, z: 8.4, tx: 0, ty: 0.3, tz: 0 },
    trail: false,
  },
  {
    id: 'intro-3',
    section: 'intro',
    kicker: '03  ·  Introduction',
    title: 'A product that adapts.',
    line: 'You choose what matters most.',
    photos: [
      { src: p('photos/yash/profile.jpg'), w: 2.0, h: 2.4, x: 3.2, y: 0.2, z: 0.3, ry: -0.16 },
      { src: p('photos/bangladesh/padma.jpg'), w: 3.4, h: 1.95, x: -3.0, y: 0.55, z: -0.8, ry: 0.12 },
    ],
    cam: { x: 0.4, y: 0.2, z: 8.0, tx: -0.1, ty: 0.2, tz: 0 },
    trail: false,
  },
  {
    id: 'vgrg-1',
    section: 'vgrg',
    kicker: '04  ·  VG & RG',
    title: 'Two conversations. One career.',
    line: 'Help clients. Build a team.',
    photos: [
      { src: p('photos/ergo/team.jpg'), w: 4.6, h: 2.7, x: 2.5, y: 0.35, z: -1.0, ry: -0.12 },
    ],
    cam: { x: -0.5, y: 0.2, z: 8.0, tx: 1.0, ty: 0.2, tz: -0.4 },
    trail: true,
  },
  {
    id: 'vgrg-2',
    section: 'vgrg',
    kicker: '04  ·  VG',
    title: 'VG — protect people’s wealth.',
    line: 'The client conversation. Security, returns, flexibility.',
    photos: [
      { src: p('photos/yash/portrait.jpg'), w: 2.15, h: 2.7, x: 3.15, y: 0.15, z: 0.2, ry: -0.14 },
      { src: p('photos/bangladesh/heritage.jpg'), w: 3.5, h: 2.0, x: -3.1, y: 0.5, z: -0.9, ry: 0.12 },
    ],
    cam: { x: 0.2, y: 0.15, z: 8.2, tx: 0, ty: 0.15, tz: 0 },
    trail: false,
  },
  {
    id: 'vgrg-3',
    section: 'vgrg',
    kicker: '04  ·  RG',
    title: 'RG — build a team that lasts.',
    line: 'This conversation. People who want more.',
    photos: [
      { src: p('photos/ergo/team.jpg'), w: 4.2, h: 2.5, x: -2.7, y: 0.4, z: -1.0, ry: 0.14 },
      { src: p('photos/yash/casual.jpg'), w: 2.6, h: 1.95, x: 3.2, y: -0.15, z: 0.3, ry: -0.16 },
    ],
    cam: { x: 0.3, y: 0.2, z: 8.3, tx: -0.2, ty: 0.15, tz: 0 },
    trail: false,
  },
  {
    id: 'earn-1',
    section: 'earn',
    kicker: '05  ·  How you earn',
    title: 'First: your own work.',
    line: 'You are paid for the clients you serve.',
    photos: [
      { src: p('photos/yash/profile.jpg'), w: 2.2, h: 2.65, x: 3.2, y: 0.2, z: 0.2, ry: -0.12 },
      { src: p('photos/bangladesh/dhaka.jpg'), w: 3.8, h: 2.15, x: -3.0, y: 0.55, z: -1.0, ry: 0.14 },
    ],
    cam: { x: 0.15, y: 0.2, z: 8.1, tx: 0.1, ty: 0.2, tz: 0 },
    trail: true,
  },
  {
    id: 'earn-2',
    section: 'earn',
    kicker: '05  ·  How you earn',
    title: 'Then: the people you lead.',
    line: 'Leadership multiplies what you already do well.',
    photos: [
      { src: p('photos/ergo/team.jpg'), w: 4.5, h: 2.65, x: 2.55, y: 0.4, z: -0.8, ry: -0.12 },
    ],
    cam: { x: -0.5, y: 0.2, z: 7.9, tx: 1.0, ty: 0.25, tz: -0.4 },
    trail: false,
  },
  {
    id: 'earn-3',
    section: 'earn',
    kicker: '05  ·  How you earn',
    title: 'Training. System. Support.',
    line: 'Tue & Thu 19:00–21:00. Sales. Recruiting. Leadership.',
    photos: [
      { src: p('photos/yash/vision.jpg'), w: 3.4, h: 3.4, x: 2.8, y: 0.15, z: -0.4, ry: -0.1 },
      { src: p('photos/bangladesh/padma.jpg'), w: 3.2, h: 1.8, x: -3.2, y: 0.6, z: -0.8, ry: 0.16 },
    ],
    cam: { x: -0.2, y: 0.15, z: 8.2, tx: 0.4, ty: 0.15, tz: 0 },
    trail: false,
  },
  {
    id: 'fragen-1',
    section: 'fragen',
    kicker: '06  ·  Fragen',
    title: 'Your turn. Ask anything.',
    line: 'No script from here. Just honesty.',
    photos: [
      { src: p('photos/yash/portrait.jpg'), w: 2.3, h: 2.9, x: 3.0, y: 0.1, z: 0.3, ry: -0.12 },
    ],
    cam: { x: -0.4, y: 0.15, z: 8.0, tx: 0.8, ty: 0.1, tz: 0 },
    trail: true,
  },
  {
    id: 'fragen-2',
    section: 'fragen',
    kicker: '06  ·  Fragen',
    title: 'Shall we start together?',
    line: 'The next step is yours.',
    photos: [
      { src: p('photos/yash/vision.jpg'), w: 3.6, h: 3.6, x: 2.6, y: 0.1, z: -0.5, ry: -0.08 },
      { src: p('photos/bangladesh/cox.jpg'), w: 3.4, h: 1.9, x: -3.3, y: 0.55, z: -0.9, ry: 0.14 },
    ],
    cam: { x: 0, y: 0.25, z: 8.5, tx: 0.2, ty: 0.15, tz: 0 },
    trail: false,
  },
];
